### ISSUE TITLE
Intégration impossible à HA

### ISSUE THREAD

**Issue by DanTsion** [DanChaltiel/heatzy-pilote-card#1]
Salut, 

J'aime beaucoup le rendu de ta carte pour afficher proprement un module heatzy, 

Cependant, je n'arrive pas du tout à installer ta carte, pourtant j'ai bien suivi ta doc. 

J'ai comparé les bundles HACS pour du front end et ils mentionnent tous un script js, suivi d'un fichier finissant par gz.

Est ce que cela a un rapport de pres ou de loin avec l'impossibilité d'installer ? 

aurais tu une consigne à suivre ? 

En tout cas un grand merci pour ton initiative et ton boulot !

**Comment by DanChaltiel** [comment]
Salut,

Merci pour tes commentaires :-)

Est-ce que tu as une erreur quelque part ?
Est-ce que tu as bien pensé à ajouter la ressource ? Chez moi aucune carte frontend HACS ne marche avec les ressources entrées par la GUI, j'ai du ajouter ça dans `configuration.yaml`:

```yaml
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/content-card-linky/content-card-linky.js
      type: module
```
