### ISSUE TITLE
Possibilité de grouper les Heatzy, comme dans l'appli officiel

### ISSUE THREAD

**Issue by Fly0017** [DanChaltiel/heatzy-pilote-card#5]
Bonjour ! 

je viens de découvrir ta card, qui est top ! J'utilisais jusque la un truc fait maison qui faisait le taff, mais le tiens est quand même plus beau :D

Par contre, je n'ai pas trouver de moyen de combiner 2 heatzy pour ne pas à avoir à les changer manuellement (comme un peu faire dans l'appli officiel) ce n'est pas présent ou je n'ai pas trouvé?

Merci d'avance.

**Comment by DanChaltiel** [comment]
Bonne idée ! 
Par exemple si on a 2 chauffages dans le salon on pourrait écrire :
```yaml 
type: custom:heatzy-pilote-card
title: Mes chauffages
language: fr
elements:
  - entities: 
      - climate.rad_salon1
      - climate.rad_salon2
    temp_sensor: sensor.salon_temperature
    friendly_name: Salon
```

Je ne sais pas trop quand j'aurai le temps de faire ça mais ça ne doit pas être très compliqué si tu veux faire une PR :-)
